### ISSUE TITLE
User Story: Publish a poll

### ISSUE THREAD

**Issue by edwardgurney** [edwardgurney/My-First-Agile-Project#2]
As an **administrator** I can **collect users feedback** so that **I can publish a poll**

## Acceptance Criteria 

* A dropdown menu for users to provide their rating out of ten.
* A comments box for additional feedback.
* A check box for anonymous submission.
* A send button to submit data. 

## Tasks

- [ ] HTML user input box with 1-10 ratings
- [ ] CSS for user input dropdown box
- [ ] HTML and CSS for user input comments box
- [ ] HTML and CSS for checkbox for user anonymity
- [ ] HTML and CSS send button. HTML sends to server database.

**Comment by edwardgurney** [comment]
## Acceptance Criteria 

* A dropdown menu for users to provide their rating out of ten.
* A comments box for additional feedback.
* A check box for anonymous submission.
* A send button to submit data. 

## Tasks

- [ ] HTML user input box with 1-10 ratings
- [ ] CSS for user input dropdown box
- [ ] HTML and CSS for user input comments box
- [ ] HTML and CSS for checkbox for user anonymity
- [ ] HTML and CSS send button. HTML sends to server database.
